version: '3'
services:
  account-service:
    build: ./account
    ports:
      - "8080:8080"
    networks:
      - microservices-net
  admin-service:
    build: ./admin
    ports:
      - "8081:8080"
    networks:
      - microservices-net
  discovery-service:
    build: ./discovery
    ports:
      - "8761:8761"
    networks:
      - microservices-net
  exchange-service:
    build: ./exchange
    ports:
      - "8082:8080"
    networks:
      - microservices-net
  gateway-service:
    build: ./gateway
    ports:
      - "8085:8080"
    networks:
      - microservices-net
  market-service:
    build: ./market
    ports:
      - "8083:8080"
    networks:
      - microservices-net
  statistics-service:
    build: ./statistics
    ports:
      - "8084:8080"
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
