version: '3'
services:
  eureka-server:
    image: 853228521229.dkr.ecr.us-east-1.amazonaws.com/coinserver/eureka-service:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  account-service:
    image: 853228521229.dkr.ecr.us-east-1.amazonaws.com/coinserver/account-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

  admin-service:
    image: 853228521229.dkr.ecr.us-east-1.amazonaws.com/coinserver/admin-service:latest
    ports:
      - "8081:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

  exchange-service:
    image: 853228521229.dkr.ecr.us-east-1.amazonaws.com/coinserver/exchange-service:latest
    ports:
      - "8082:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

  gateway-service:
    image: 853228521229.dkr.ecr.us-east-1.amazonaws.com/coinserver/gateway-service:latest
    ports:
      - "8085:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

  market-service:
    image: 853228521229.dkr.ecr.us-east-1.amazonaws.com/coinserver/market-service:latest
    ports:
      - "8083:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

  statistics-service:
    image: 853228521229.dkr.ecr.us-east-1.amazonaws.com/coinserver/statistics-service:latest
    ports:
      - "8084:8080"
    depends_on:
      - eureka-server
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
