server:
  port: 8085
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: account
          uri: http://localhost:8080
          predicates:
            - Path=/auth/**
            - Path=/profile/**
          filters:
            - JwtAuthenticationFilter
        - id: market
          uri: http://localhost:8083
          predicates:
            - Path=/market/**
            - Path=/trades/**
          filters:
            - JwtAuthenticationFilter

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
